extension Character {
    static let tab = Character("\t")
    static let lf = Character("\n")
    static let cr = Character("\r")
    static let crLf = Character("\r\n")
    static let space = Character(" ")
    static let exclamation = Character("!")
    static let dollar = Character("$")
    static let percent = Character("%")
    static let ampersand = Character("&")
    static let leftParen = Character("(")
    static let rightParen = Character(")")
    static let asterisk = Character("*")
    static let plus = Character("+")
    static let comma = Character(",")
    static let minus = Character("-")
    static let dot = Character(".")
    static let slash = Character("/")
    static let _0 = Character("0")
    static let _9 = Character("9")
    static let colon = Character(":")
    static let semicolon = Character(";")
    static let leftAngleBracket = Character("<")
    static let equal = Character("=")
    static let rightAngleBracket = Character(">")
    static let question = Character("?")
    static let A = Character("A")
    static let Z = Character("Z")
    static let leftSquareBracket = Character("[")
    static let backslash = Character("\\")
    static let rightSquareBracket = Character("]")
    static let underscore = Character("_")
    static let a = Character("a")
    static let z = Character("z")
    static let leftBrace = Character("{")
    static let pipe = Character("|")
    static let rightBrace = Character("}")
}
