name: test

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - run: sudo $GITHUB_WORKSPACE/ci/install-swift.bash
        working-directory: /home/runner
      - run: swift --version

      - run: swift package resolve
      - run: swift build
      - run: swift test
